# Generated by Django - Initial migration for activities app

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('package', 'Package'), ('activity', 'Activity'), ('transport', 'Transport'), ('accommodation', 'Accommodation')], default='activity', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['category', 'display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BookingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.activity')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_activities', to='bookings.booking')),
            ],
            options={
                'unique_together': {('booking', 'activity')},
            },
        ),
    ]
